version: "3"

services:

  ble:
    container_name: pibeacon
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5551:5551"
    network_mode: host
